name: Update Calendar

on:

  workflow_dispatch:

  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python main.py

        env:
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}

      - name: Commit ICS

        run: |

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add eventbrite.ics

          git diff --cached --quiet && exit 0

          git commit -m "Update calendar"

          git push